### ISSUE TITLE
problems with undefined variable

### ISSUE THREAD

**Issue by ritapas** [evently-nl/GDPRDeleteToken#1]
I added a 
$uriCorrect = false;

@line 115 in MY copy of the source code.

Sorry but I'm not familiar with github to submit a change

**Comment by ritapas** [comment]
BTW I would love to have a way to put a shortcut for the Survey administrator's email addresses inside the "GDPR e-mail" field in the plugin config.

**Comment by evently-nl** [comment]
Hi,

Could you describe the issue at the moment and how to replicate? You have your fork set to private I guess, as I can't see your code.

If you pushed your commits to your fork, you can create a pull request from github, which I can (if everything is working alright) merge into the plugin. 

Cheers! 

Ps I'll look into the feature request, but if you would make a working pull request I'll accept as well!

**Comment by ritapas** [comment]
Hello,
when an invitation is sent, I receive the following error message:
**Notice:** Undefined variable: uriCorrect in **/var/www/limesurvey/plugins/GDPRDeleteToken/GDPRDeleteToken.php** on line **122**

This is likely because I set debug=1 in the config.php file - indeed it does not happen if debug=0!

I have no fork of your project, the copy I have edited is in our own filesystem.
I wish I could contribute more/better but I am not a PHP developer...

Thank you a lot.
Rita

**Comment by evently-nl** [comment]
Hi Rita, 
That makes sense! I will test this myself today and create a fix. 

No problem about not being able to create a pull request, thanks for the clear description!
