### ISSUE TITLE
Cannot customize the "Link text"

### ISSUE THREAD

**Issue by ritapas** [evently-nl/GDPRDeleteToken#3]
Hello,
I see that the link included in the invitation message has always the mere url to the remove page, whatever text you put in the "Link text" field of the configuration page.

Email template:
![immagine](https://user-images.githubusercontent.com/16462671/90229022-824e3900-de17-11ea-9d68-06da7dfca624.png)

Plugin Configuration page:
![immagine](https://user-images.githubusercontent.com/16462671/90228336-567e8380-de16-11ea-86c4-2d00e4cbd854.png)

Message received:
![immagine](https://user-images.githubusercontent.com/16462671/90229178-c2152080-de17-11ea-8378-db9c95035824.png)

**Comment by ritapas** [comment]
I'd also love to have a way to translate the text according to participants' language!

**Comment by evently-nl** [comment]
Thanks for the notice. I will have a look at the link text bug next week, as well as at translating the texts.

**Comment by evently-nl** [comment]
Fixed the first part: using @@TOKENREMOVE@@ (with 2 '@'s) will replace the text in the email with the proper text from the settings. 

Using the @@@TOKENREMOVE@@@ is still replaced with the entire url only (so you can use it to create your own buttons or links)

I will take a look at more extensive translation options, need to check if you can have options in plugins based on the number of langauges added to a survey.

**Comment by ritapas** [comment]
That would be great. Please let me know if I can help with testing.
